name: mpv
base: core22
adopt-info: mpv
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64

apps:
  mpv:
    command: usr/bin/mpv
    extensions: [gnome]
    common-id: io.mpv.Mpv
    desktop: usr/share/applications/mpv.desktop
    plugs:
      - audio-playback
      - home
      - network
      - removable-media
      - optical-drive
    slots:
      - mpris

parts:
  mpv:
    source: https://github.com/mpv-player/mpv.git
    source-tag: v0.35.1
    after: [ffmpeg]
    parse-info: [usr/share/metainfo/mpv.metainfo.xml]
    plugin: meson
    meson-parameters:
      - -Dlibmpv=true
      - -Dmanpage-build=disabled
      - -Dalsa=disabled
      - -Dcdda=enabled
      - -Ddvbin=enabled
      - -Ddvdnav=enabled
      - -Dlibarchive=enabled
      - -Dsdl2=enabled
      - -Dshaderc=enabled
      - -Dvulkan=enabled
      - -Dprefix=/usr
      - -Dbuildtype=release
      - -Dbuild-date=false
      - -Dlua=enabled
      - -Dpulse=enabled
      - -Ddrm=enabled
      - -Degl=enabled 
      - -Degl-wayland=enabled
      - -Dwayland=enabled
      - -Dvaapi-wayland=enabled 
      - -Dvaapi-drm=enabled 
      - -Dvaapi-x11=enabled 
      - -Dvaapi-x-egl=enabled
      - -Dx11=enabled
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | cut -c 2-)
    build-snaps:
      - cmake
      - ubuntu-make
    build-packages:
      - libavfilter-dev
      - libass-dev
      - libpulse-dev
      - libdrm-dev
      - libwayland-dev
      - wayland-protocols
      - libxkbcommon-dev
      - libegl1-mesa-dev
      - libva-dev
      - liblua5.2-dev
      - libcdio++-dev
      - libcdio-dev
      - libcdio-paranoia-dev
      - libdvdnav-dev
      - libmujs-dev
      - libsdl2-dev
      - libarchive-dev
      - build-essential
      - libjpeg-dev
      - librubberband-dev
    stage-packages:
      - libva-wayland2
      - liblua5.2-0
    
  ffmpeg:
    # WORKAROUND:
    # Build from source because the ffmpeg package installs libraries as dependencies
    # that conflict with the Gnome extension
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
    autotools-configure-parameters:
      # WORKAROUND: Install to /usr instead of /usr/local because it's not in search paths
      - --prefix=/usr
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-avcodec
      - --enable-gpl
      - --enable-shared
      - --disable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
      - --enable-avformat  
      - --enable-libaom
      - --enable-swresample
      - --enable-libfdk-aac
      - --enable-nonfree
      - --enable-libass
      - --enable-libbluray
    build-packages:
      - nasm
      - libgnutls28-dev
      - libfdk-aac-dev
      - libmp3lame-dev
      - libavformat-dev
      - libvorbis-dev
      - libavcodec-dev
      - libaom-dev
      - libswresample-dev
      - libass-dev
      - libbluray-dev
    stage-packages:
      - libmp3lame0
      - libaom3
      - libfdk-aac2
      - libass9
      - libbluray2
      - libudfread0
    stage:
      - -usr/include

