name: mpv
adopt-info: mpv
base: core22
grade: stable
confinement: strict
compression: lzo

apps:
  mpv:
    command: usr/bin/mpv
    extension: [gnome]
    common-id:
    desktop:
    plugs:
    - audio-playback
    - home
    - network
    - removable-media
    - optical-drive

parts:
  mpv:
    source: https://github.com/mpv-player/mpv/archive/v0.35.1.tar.gz
    plugin: meson
    meson-parameters:
    - -Dprefix=/usr
    - -Dbuildtype=release
    - -Dbuild-date=false
    - -Dlua=enabled
    - -Dpulse=enabled
    - -Ddrm=enabled
    - -Degl=enabled -Degl-wayland=enabled
    - -Dwayland=enabled
    - -Dvaapi-wayland=enabled -Dvaapi-drm=enabled -Dvaapi-x11=enabled -Dvaapi-x-egl=enabled
    - -Dx11=enabled
    override-pull: |
      craftctl default
      sed '1224s/MPMIN(ver, 4)/MPMIN(ver, 3)/' -i video/out/wayland_common.c
    build-packages:
    - pkg-config
    - libavfilter-dev
    - libass-dev
    - libpulse-dev
    - libdrm-dev
    - libwayland-dev
    - wayland-protocols
    - libxkbcommon-dev
    - libegl1-mesa-dev
    - libva-dev
    - liblua5.2-dev
    stage-packages:
    - libavfilter7
    - libva-wayland2
    - liblua5.2-0
    
